# Generated by Django 4.2.30 on 2026-06-30 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_roll_number_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 50)),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
