# Generated by Django 4.2.30 on 2026-06-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_timetable_end_time_timetable_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
