# Generated by Django 4.2.30 on 2026-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_timetable_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='subject_category',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Practical', 'Practical'), ('Seminar', 'Seminar')], default='Theory', max_length=20),
        ),
    ]
