# Generated by Django 4.2.30 on 2026-07-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_timetable_subject_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject_category',
        ),
    ]
