# Generated by Django 4.2.30 on 2026-06-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_designation_alter_faculty_employee_id'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='reviewed_at',
            new_name='advisor_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='advisor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='advisor_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_reviewed_leaves', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_reviewed_leaves', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_advisor', 'Pending Advisor Approval'), ('pending_hod', 'Pending HOD Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_advisor', max_length=20),
        ),
    ]
