# Generated by Django 4.2.30 on 2026-07-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_designation_alter_faculty_employee_id'),
        ('students', '0004_alter_timetable_section'),
        ('leave', '0002_rename_reviewed_at_leaverequest_advisor_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='from_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_partial_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacultyODAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('from_period', models.IntegerField(blank=True, null=True)),
                ('to_period', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ods', to='faculty.faculty')),
                ('students', models.ManyToManyField(related_name='assigned_ods', to='students.student')),
            ],
        ),
    ]
