# Generated by Django 4.2.30 on 2026-07-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_from_period_leaverequest_is_partial_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('medical', 'Medical'), ('personal', 'Personal'), ('academic', 'Academic'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20),
        ),
    ]
