# Generated by Django 4.2.30 on 2026-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTiming',
            fields=[
                ('period_number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['period_number'],
            },
        ),
    ]
